#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  BALANCE & RENTALS LAB"
echo "  Run from your LAPTOP"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  1. Launch VPOD Admin Interface"
echo ""
echo "  2. Get an Org UUID (from previous lab or lookup)"
echo ""
echo "  3. Check their balance:"
echo "     Admin API → Organizations → Get Balance by Org ID"
echo ""
echo "  4. View their rentals:"
echo "     Admin API → Organizations → Baremetal Rentals by Org ID"
echo ""
echo "  5. Get server IPs:"
echo "     Admin API → Organizations → Baremetal Nodes by Org ID"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
