#!/bin/bash
# Log Collection via Node Toolkit Lab
# This prints instructions only - no SSH needed

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  LOG COLLECTION VIA NODE TOOLKIT"
echo "  Run from your LAPTOP (not the server)"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  PREREQUISITE: VOLT API Key"
echo "  Node Toolkit uses the VOLT API for node discovery."
echo "  Generate your key at: https://volt.lightning.ai/settings"
echo ""
echo "  STEPS:"
echo ""
echo "  1. Open a terminal on your laptop"
echo ""
echo "  2. Navigate to Support-Tooling:"
echo "     cd ~/Github/Support-Tooling"
echo ""
echo "  3. Start Node Toolkit:"
echo "     ./scripts/sshv/start-node-toolkit.sh"
echo ""
echo "  4. Enter hostname or use discovery to find the node"
echo ""
echo "  5. From Main Menu:"
echo "     → 14 (Log Collection)"
echo "     → 1  (Collect dmesg)"
echo "     → 2  (Collect journalctl)"
echo ""
echo "  6. Check ~/Reports/ for collected logs"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
