#!/bin/bash
echo ""
echo "✓ Lab complete!"
echo ""
echo "  Logs are saved to: ~/Reports/<hostname>/"
echo ""
echo "  Quick reference:"
echo "  • Option 1: dmesg"
echo "  • Option 2: journalctl"
echo "  • Option 9: Collect all standard logs (parallel)"
echo ""
echo "  Use Node Toolkit for day-to-day log collection."
echo "  Use manual commands when you need one specific thing fast."
echo ""
