#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  EXPLORE VOLT LAB"
echo "  Web-based - open in your browser"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  1. Open VOLT: https://volt.lightning.ai"
echo ""
echo "  2. Search for a hostname (e.g., the one in your ticket)"
echo ""
echo "  3. Find:"
echo "     - Which datacenter (DC)"
echo "     - Which cluster"
echo "     - Customer name"
echo "     - iDRAC IP"
echo ""
echo "  4. Click the row to see full details"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
