#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  REDFISH HEALTH CHECK LAB"
echo "  Run from your LAPTOP"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  1. Open a terminal on your laptop"
echo "  2. Navigate to Support-Tooling:"
echo "     cd ~/Github/Support-Tooling"
echo "  3. Run the Redfish script:"
echo "     ./scripts/api/connect-idrac-via-redfish.sh"
echo "  4. Select datacenter → Enter hostname → System Info & Health"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
