#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  TSR COLLECTION LAB"
echo "  Run from your LAPTOP via Node Toolkit"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  1. Launch Node Toolkit:"
echo "     cd ~/Github/Support-Tooling"
echo "     ./scripts/sshv/start-node-toolkit.sh"
echo ""
echo "  2. Connect to a node (or use discovery)"
echo ""
echo "  3. Main Menu → 14 (Log Collection) → 7 (TSR)"
echo ""
echo "  4. Wait for collection to complete (~5-10 min)"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
