#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  CUSTOMER LOOKUP LAB"
echo "  Run from your LAPTOP"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  1. Launch VPOD Admin Interface:"
echo "     cd ~/Github/Support-Tooling"
echo "     ./scripts/api/start-vpod-admin-interface.sh"
echo ""
echo "  2. Admin API → Users → Get User by Email"
echo ""
echo "  3. Copy the Org UUID from the result"
echo ""
echo "  4. Admin API → Organizations → Get Org by ID"
echo ""
echo "  When done, click 'Mark Complete' in the web UI."
echo "═══════════════════════════════════════════════════════"
echo ""
